i18n:
    structure: multiple_files
    locales: [en, es]
    default_locale: en
backend:
    name: github
    repo: Monknow/monknow.dev
    branch: master
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
site_url: https://www.monknow.dev
display_url: https://www.monknow.dev
logo_url: https://www.monknow.dev/static/237fb7a3582df41fbbe11d2032729a66/fa07f/android-chrome-512x512.png
collections:
    - name: blog
      folder: "src/pages/blog"
      path: "{{slug}}/index"
      media_folder: ""
      public_folder: ""
      label: Blog
      i18n: true
      extension: md
      format: frontmatter
      create: true
      identifier_field: slug
      slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
      fields:
          - {name: tipo, label: Tipo, widget: hidden, required: true, i18n: duplicate, default: blog}
          - {
                name: slug,
                label: Slug,
                widget: string,
                required: true,
                pattern: ["[A-z0-9 ]+(?:-[A-z0-9 ]+)*", "A slug can't have special characters"],
                i18n: duplicate,
            }
          - {name: fecha, label: Fecha, widget: datetime, i18n: duplicate}
          - {name: titulo, label: Titulo, required: true, i18n: true}
          - {name: subtitulo, label: Subtitulo, required: true, i18n: true}
          - {
                name: portada,
                label: Portada,
                widget: image,
                required: true,
                allow_multiple: false,
                choose_url: false,
                i18n: true,
            }
          - {name: descripcionImagen, label: Descripción de Imagen, required: true, i18n: true}
          - {name: atribucionImagen, label: Atribución de Imagen, required: false, i18n: true}
          - {name: urlAtribucionImagen, label: URL de atribucion de Imagen, required: false, i18n: true}
          - {name: descripcion, label: Descripcion del Post (SEO), widget: string, required: true, i18n: true}
          - {name: body, label: Cuerpo, widget: markdown, required: true, i18n: true}
    - name: portafolio
      label: Portafolio
      folder: "src/pages/portfolio"
      path: "{{slug}}/index"
      media_folder: ""
      public_folder: ""
      extension: md
      format: frontmatter
      i18n: true
      create: true
      identifier_field: slug
      slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
      fields:
          - {name: tipo, label: Tipo, widget: hidden, required: true, i18n: duplicate, default: portafolio}
          - {
                name: slug,
                label: Slug,
                widget: string,
                required: true,
                pattern: ["[A-z0-9 ]+(?:-[A-z0-9 ]+)*", "A slug can't have special characters"],
                i18n: duplicate,
            }
          - {name: titulo, label: Titulo, required: true, i18n: true}
          - {name: subtitulo, label: Subtitulo, required: true, i18n: true}
          - {
                name: portada,
                label: Portada,
                widget: image,
                required: true,
                allow_multiple: false,
                choose_url: false,
                i18n: true,
            }
          - {name: descripcionImagen, label: Descripción de Imagen, required: true, i18n: true}
          - {name: url, label: URL, required: true, i18n: true}
