i18n:
    structure: multiple_folders
    locales: [en, es]
    default_locale: en
backend:
    name: github
    repo: Monknow/monknow.dev
    branch: master
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
site_url: https://www.monknow.dev
display_url: https://www.monknow.dev
logo_url: https://www.monknow.dev/static/237fb7a3582df41fbbe11d2032729a66/fa07f/android-chrome-512x512.png
collections:
    - name: blog
      identifier_field: slug
      folder: "src/pages/blog"
      label: Blog
      i18n: true
      create: true
      slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
      fields:
          - {name: slug, label: Slug, i18n: duplicate}
          - {name: fecha, label: Fecha, widget: datetime, i18n: duplicate}
          - {name: titulo, label: Titulo, i18n: true}
          - {name: subtitulo, label: Subtitulo, i18n: true}
          - {name: portada, label: Portada, widget: image, i18n: true}
          - {name: descripcionImagen, label: Descripción de Imagen, i18n: true}
          - {name: atribucionImagen, label: Atribución de Imagen, i18n: true, required: false}
          - {name: urlAtribucionImagen, label: URL de atribucion de Imagen, i18n: true, required: false}
          - {name: cuerpo, label: Cuerpo, widget: markdown, i18n: true}
    - name: portafolio
      identifier_field: slug
      folder: "src/pages/portfolio"
      label: Portafolio
      i18n: true
      create: true
      slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
      fields:
          - {name: slug, label: Slug, i18n: duplicate}
          - {name: titulo, label: Titulo, i18n: true}
          - {name: subtitulo, label: Subtitulo, i18n: true}
          - {name: portada, label: Portada, widget: image, i18n: true}
          - {name: descripcionImagen, label: Descripción de Imagen, i18n: true}
          - {name: url, label: URL, i18n: true}
